version: "3.6"
services:

  wordpress:    
    image: wp-image
    restart: always    
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    ports:
      - 8000:80
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - .:/docker-entrypoint-initdb.d

volumes:
  mysql: {}